server {
    listen 8000;

    root /app;
    index index.html;

    location = /bridge.html {
        try_files /bridge.html =404;
        add_header Content-Type "text/html; charset=utf-8";
        add_header Cache-Control "no-store, no-cache";
        add_header X-Content-Type-Options "nosniff";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}