server {
    listen 8000;

    root /app;
    index index.html;

    location = /bridge.html {
        root /app/assets;
        try_files /bridge.html =404;
        add_header Content-Type text/html;
        add_header Cache-Control no-store;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}