server {
    listen 8000;

    root /app;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /bridge.html {
        alias /app/assets/bridge.html;
        add_header Content-Type text/html;
    }
}